In [1]:
import pandas as pd

In [48]:
df= pd.read_csv("AidDataCoreThin_ResearchRelease_Level1_v3.1.csv")
df.head()

,aiddata_id,aiddata_2_id,year,donor,recipient,commitment_amount_usd_constant,coalesced_purpose_code,coalesced_purpose_name
0,1,NaN,2003,African Development Bank (AFDB),Togo,29589911,24030,Formal sector financial intermediaries
1,2,NaN,1990,African Development Bank (AFDB),Burundi,9713596,31100,"Agriculture, combinations of purposes in Agric..."
2,3,NaN,1991,African Development Bank (AFDB),Cote d`Ivoire,148139421,31120,Agricultural development
3,4,NaN,1992,African Development Bank (AFDB),Cameroon,24693752,31120,Agricultural development
4,5,NaN,1992,African Development Bank (AFDB),Gabon,82312507,31100,"Agriculture, combinations of purposes in Agric..."

In [52]:
df1=df.groupby(['coalesced_purpose_name']).count().sort_values(['year'], ascending=False)
purpose=df1.head(5).index
purpose

Index(['Sectors not specified', 'Strengthening civil society',
       'Multisector aid', 'Social/ welfare services', 'Higher education'],
      dtype='object', name='coalesced_purpose_name')

In [54]:
purpose[0]

'Sectors not specified'

In [56]:
purpose[4]

'Higher education'

In [69]:
dfnew=df[(df.coalesced_purpose_name == purpose[0]) | (df.coalesced_purpose_name == purpose[1]) 
         |(df.coalesced_purpose_name == purpose[2])| (df.coalesced_purpose_name == purpose[3]) | (df.coalesced_purpose_name == purpose[4])]

In [70]:
dfnew.head()

,aiddata_id,aiddata_2_id,year,donor,recipient,commitment_amount_usd_constant,coalesced_purpose_code,coalesced_purpose_name
61,635599,NaN,1991,African Development Bank (AFDB),Mauritius,22582229,43010,Multisector aid
72,635610,NaN,1991,African Development Bank (AFDB),Seychelles,9032892,43010,Multisector aid
155,635695,NaN,1982,African Development Bank (AFDB),Malawi,14566803,43010,Multisector aid
167,635707,NaN,1982,African Development Bank (AFDB),Zambia,29133607,43010,Multisector aid
231,635771,NaN,1988,African Development Bank (AFDB),Mauritius,12124606,43010,Multisector aid

In [72]:
dfsubset=dfnew[['donor','commitment_amount_usd_constant','coalesced_purpose_name']]
dfsubset

,donor,commitment_amount_usd_constant,coalesced_purpose_name
61,African Development Bank (AFDB),22582229,Multisector aid
72,African Development Bank (AFDB),9032892,Multisector aid
155,African Development Bank (AFDB),14566803,Multisector aid
167,African Development Bank (AFDB),29133607,Multisector aid
231,African Development Bank (AFDB),12124606,Multisector aid
233,African Development Bank (AFDB),21936924,Social/ welfare services
235,African Development Bank (AFDB),145495273,Multisector aid
285,African Development Fund (AFDF),10886319,Multisector aid
335,African Development Bank (AFDB),53403628,Multisector aid
387,African Development Fund (AFDF),60768924,Multisector aid
477,Caribbean Development Bank (CDB),1906576,Multisector aid
486,Caribbean Development Bank (CDB),838561,Multisector aid
504,Caribbean Development Bank (CDB),377353,Multisector aid
519,Caribbean Development Bank (CDB),1358471,Sectors not specified
546,Caribbean Development Bank (CDB),1741155,Multisector aid
551,Caribbean Development Bank (CDB),233315,Multisector aid
563,Caribbean Development Bank (CDB),9119391,Multisector aid
628,Asian Development Fund (ASDF),234752118,Multisector aid
643,Asian Development Fund (ASDF),32534757,Multisector aid
670,Asian Development Bank (ASDB),98145353,Multisector aid
711,Caribbean Development Bank (CDB),6374664,Multisector aid
720,Caribbean Development Bank (CDB),7923128,Multisector aid
734,Caribbean Development Bank (CDB),4350599,Multisector aid
736,Caribbean Development Bank (CDB),1859955,Multisector aid
737,Caribbean Development Bank (CDB),3188494,Multisector aid
756,Caribbean Development Bank (CDB),11309822,Multisector aid
767,Asian Development Fund (ASDF),2503323,Multisector aid
769,Asian Development Fund (ASDF),5317716,Multisector aid
927,Caribbean Development Bank (CDB),2002658,Multisector aid
967,Asian Development Bank (ASDB),56875117,Higher education
...,...,...,...
1560637,World Bank - International Bank for Reconstruc...,200000,Higher education
1560660,World Bank - International Bank for Reconstruc...,36000000,Social/ welfare services
1560675,World Bank - International Bank for Reconstruc...,10000000,Social/ welfare services
1560691,World Bank - International Bank for Reconstruc...,34750628,Strengthening civil society
1560693,World Bank - International Bank for Reconstruc...,56214251,Strengthening civil society
1560703,World Bank - International Bank for Reconstruc...,51103864,Strengthening civil society
1560717,World Bank - International Bank for Reconstruc...,202371303,Higher education
1560725,World Bank - International Bank for Reconstruc...,18397391,Strengthening civil society
1560732,World Bank - International Bank for Reconstruc...,45993478,Strengthening civil society
1560744,World Bank - International Bank for Reconstruc...,100163574,Strengthening civil society
1560756,World Bank - International Bank for Reconstruc...,245298549,Social/ welfare services
1560769,World Bank - International Bank for Reconstruc...,40883092,Higher education
1560778,World Bank - International Bank for Reconstruc...,39349976,Social/ welfare services
1560816,World Bank - International Bank for Reconstruc...,44971401,Social/ welfare services
1560828,World Bank - International Bank for Reconstruc...,5110386,Social/ welfare services
1560845,World Bank - International Bank for Reconstruc...,1430908,Social/ welfare services
1560870,World Bank - International Bank for Reconstruc...,36334848,Social/ welfare services
1560874,World Bank - International Bank for Reconstruc...,23252258,Higher education
1560891,World Bank - International Bank for Reconstruc...,8994280,Social/ welfare services
1560912,World Bank - International Bank for Reconstruc...,3593215,Higher education
1560922,World Bank - International Bank for Reconstruc...,51103864,Social/ welfare services
1560932,World Bank - International Bank for Reconstruc...,4037205,Strengthening civil society
1560949,World Bank - International Bank for Reconstruc...,4292725,Social/ welfare services
1560965,World Bank - International Bank for Reconstruc...,50490618,Social/ welfare services
1560971,World Bank - International Bank for Reconstruc...,11242850,Social/ welfare services
1560979,World Bank - International Bank for Reconstruc...,3679478,Higher education
1560981,World Bank - International Bank for Reconstruc...,25551932,Higher education
1560997,World Bank - International Bank for Reconstruc...,100163574,Social/ welfare services
1561014,World Bank - International Bank for Reconstruc...,22485700,Higher education
1561021,World Bank - International Bank for Reconstruc...,95053188,Social/ welfare services

In [73]:
dfsubset.to_csv("subset", encoding='utf-8', index=False)